### PR TITLE
github: bump docker login-action to v3

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by marquiz** [comment]
These just keep on coming... I really hope and believe this is the last one on this front for a while

**Comment by mythi** [comment]
> These just keep on coming... I really hope and believe this is the last one on this front for a while

dependabot can handle these automatically for you.

**Comment by marquiz** [comment]
> dependabot can handle these automatically for you.

But it didn't. And we don't have ops to edit the project settings so 🤷🏽‍♂️

**Review by klihub — APPROVED** [review]

**Comment by mythi** [comment]
> > dependabot can handle these automatically for you.
> 
> But it didn't. And we don't have ops to edit the project settings so 🤷🏽‍♂️

We enable it through: https://github.com/intel/intel-device-plugins-for-kubernetes/blob/d01fb6d9054cc962ba5d5f73f80e36a2ac26ec7e/.github/dependabot.yml#L11-L16

**Pull request merged**
