### PR TITLE
Fix SST discovery

### PR DESCRIPTION
**Pull request by jukkar**
This fixes compilation error because goresctrl SST discovery API was changed and now we are using the latest version.

### CODE REVIEW

**Review by marquiz — CHANGES_REQUESTED** [review]
Please run `go mod tidy` after updating go.mod

**Comment by jukkar** [comment]
> Please run `go mod tidy` after updating go.mod

done

**Review by marquiz — APPROVED** [review]
Thanks @jukkar 👍 It was about time to update goresctrl...
lgtm

**Review by klihub — APPROVED** [review]
LGTM.

**Pull request merged**
