### PR TITLE
0.6.0 release preparation: use latest fedora image for cross-build.

### PR DESCRIPTION
**Pull request by klihub**
dockerfiles: use fedora:latest for cross-builds.

### CODE REVIEW

**Comment by askervin** [comment]
Just to understand consequences... is it possible that this change results in a dependency to so new libc version that prevents running cri-resmgr on some Fedora versions that would have been supported otherwise?

**Review by marquiz — APPROVED** [review]
lgtm

**Comment by marquiz** [comment]
> Just to understand consequences... is it possible that this change results in a dependency to so new libc version that prevents running cri-resmgr on some Fedora versions that would have been supported otherwise?

Isn't `fedora` and `fedora:latest` basically the same thing? 🧐

**Comment by klihub** [comment]
> > Just to understand consequences... is it possible that this change results in a dependency to so new libc version that prevents running cri-resmgr on some Fedora versions that would have been supported otherwise?
> 
> Isn't `fedora` and `fedora:latest` basically the same thing? monocle_face

Beats me... I thought it should be, but apparently not always. Without adding that explicit `latest` tag, it was always building for me with `fedora:32`, which was the image I had readily available on my machine. That is why I added the explicit tag.

**Review by askervin — APPROVED** [review]
LGTM

**Comment by klihub** [comment]
> Just to understand consequences... is it possible that this change results in a dependency to so new libc version that prevents running cri-resmgr on some Fedora versions that would have been supported otherwise?

Yes, of course that is possible. This is for cross-building against the latest released stable fedora cloud image, not any fixed version (hence the plain `fedora` suffix). If we wanted to build for a particular fixed version, we'd need to add versioned cross-build and other related collateral for that.

**Review by marquiz — APPROVED** [review]
> Beats me... I thought it should be, but apparently not always. Without adding that explicit latest tag, it was always building for me with fedora:32,

Ah, yes it behaves that way
lgtm

**Pull request merged**
