### PR TITLE
e2e: add support for multiple dies per CPU package in numanodes

### PR DESCRIPTION
**Pull request by askervin**
Example: create a system with 2 CPU packages, 2 dies per package, 2 NUMA nodes per die, and 2 CPUs & 1G RAM per NUMA node. (16 CPUs and 8 NUMA nodes in total.)
```
$ numanodes='[{"cpu": 2, "mem": "1G", "nodes": 2, "dies": 2, "packages": 2}]' vm=c2n2d2p2 ./run.sh test
```

Result:
```
ubuntu@c2n2d2p2:~$ for cpu in /sys/devices/system/cpu/cpu[0-9]*; do echo "p:$(< ${cpu}/topology/physical_package_id) d:$(< ${cpu}/topology/die_id) c:$(< ${cpu}/topology/core_id) ${cpu}" ; done | sort 2>/dev/null
p:0 d:0 c:0 /sys/devices/system/cpu/cpu0
p:0 d:0 c:1 /sys/devices/system/cpu/cpu1
p:0 d:0 c:2 /sys/devices/system/cpu/cpu2
p:0 d:0 c:3 /sys/devices/system/cpu/cpu3
p:0 d:1 c:0 /sys/devices/system/cpu/cpu4
p:0 d:1 c:1 /sys/devices/system/cpu/cpu5
p:0 d:1 c:2 /sys/devices/system/cpu/cpu6
p:0 d:1 c:3 /sys/devices/system/cpu/cpu7
p:1 d:0 c:0 /sys/devices/system/cpu/cpu8
p:1 d:0 c:1 /sys/devices/system/cpu/cpu9
p:1 d:0 c:2 /sys/devices/system/cpu/cpu10
p:1 d:0 c:3 /sys/devices/system/cpu/cpu11
p:1 d:1 c:0 /sys/devices/system/cpu/cpu12
p:1 d:1 c:1 /sys/devices/system/cpu/cpu13
p:1 d:1 c:2 /sys/devices/system/cpu/cpu14
p:1 d:1 c:3 /sys/devices/system/cpu/cpu15
root@c2n2d2p2:~# numactl -H                                                                                                                                                                                 available: 8 nodes (0-7)
node 0 cpus: 0 1
node 0 size: 1006 MB
node 0 free: 518 MB
node 1 cpus: 2 3
node 1 size: 1007 MB
node 1 free: 445 MB
node 2 cpus: 4 5
node 2 size: 943 MB
node 2 free: 241 MB
node 3 cpus: 6 7
node 3 size: 983 MB
node 3 free: 435 MB
node 4 cpus: 8 9
node 4 size: 1007 MB
node 4 free: 547 MB
node 5 cpus: 10 11
node 5 size: 1007 MB
node 5 free: 458 MB
node 6 cpus: 12 13
node 6 size: 1007 MB
node 6 free: 380 MB
node 7 cpus: 14 15
node 7 size: 1006 MB
node 7 free: 191 MB
node distances:
node   0   1   2   3   4   5   6   7
  0:  10  20  20  20  20  20  20  20
  1:  20  10  20  20  20  20  20  20
  2:  20  20  10  20  20  20  20  20
  3:  20  20  20  10  20  20  20  20
  4:  20  20  20  20  10  20  20  20
  5:  20  20  20  20  20  10  20  20
  6:  20  20  20  20  20  20  10  20
  7:  20  20  20  20  20  20  20  10
```

### CODE REVIEW

**Comment by kad** [comment]
@askervin comment about distances: it would be good to emulate distances reported somehow closer to real systems.

**Comment by askervin** [comment]
@klihub , `topology` replaces `numanodes` now. Topology JSON supports threads. The default is two threads per core. The ambiguous `cpu` key changed to `cores` in the JSON. So now you can specify `mem`, `threads`, `cores`, `nodes`, `dies` and `packages`.

@kad, I added `dist-same-die`, `dist-same-package` and `dist-other-package` to the `topology` description to ease configuring realistic distances. The defaults used in the tests result in:
```
root@crirm-test-numa:~# numactl -H
available: 5 nodes (0-4)                                                                                                                                                                                    node 0 cpus: 0 1
node 0 size: 1006 MB
node 0 free: 623 MB                                                                                                                                                                                         node 1 cpus: 2 3
node 1 size: 1007 MB
node 1 free: 901 MB
node 2 cpus: 4 5
node 2 size: 1951 MB
node 2 free: 1648 MB
node 3 cpus: 6 7
node 3 size: 2015 MB
node 3 free: 1895 MB
node 4 cpus:
node 4 size: 8039 MB
node 4 free: 8030 MB
node distances:
node   0   1   2   3   4
  0:  10  11  21  21  21
  1:  11  10  21  21  21
  2:  21  21  10  11  11
  3:  21  21  11  10  11                                                                                                                                                                                      4:  21  21  11  11  10
```
The default `topology` specification in `test/numa/run.sh` is:
```
    {"mem": "1G", "cores": 1, "nodes": 2},
    {"mem": "2G", "cores": 1, "nodes": 2},
    {"nvmem": "8G"}
```
That is: test system has two packages, each package contains one die. Each die has two NUMA nodes. Each NUMA node has one CPU core. Each core runs two threads.

**Comment by kad** [comment]
@askervin in last example, node 4 with pmem has different distances compared to what is seen on real hardware.

**Comment by askervin** [comment]
> @askervin in last example, node 4 with pmem has different distances compared to what is seen on real hardware.

Fixed the default NUMA topology to be closer to real HW. The default definition is now
```
[
    {"mem": "1G", "cores": 1, "nodes": 2, "packages": 2, "node-dist": {"4": 28, "5": 28}},
    {"nvmem": "8G", "node-dist": {"5": 28}},
    {"nvmem": "8G"}
]
```

This results in CPU package/die/node/core/thread topology:
```
$ ./run.sh test
...
$ topology_dump=$(ssh ubuntu@172.17.4 "$(topology.py bash_topology_dump)") topology.py cpus
package0 die0 node0 core000 thread0 cpu000
                            thread1 cpu001
              node1 core001 thread0 cpu002
                            thread1 cpu003
package1 die0 node2 core000 thread0 cpu004
                            thread1 cpu005
              node3 core001 thread0 cpu006
                            thread1 cpu007
```
Node distances in resulting VM:
```
$ ssh ubuntu@172.17.4 "$(topology.py bash_topology_dump)" | grep dist
node dist 0: 10 11 21 21 28 28
node dist 1: 11 10 21 21 28 28
node dist 2: 21 21 10 11 28 28
node dist 3: 21 21 11 10 28 28
node dist 4: 28 28 28 28 10 28
node dist 5: 28 28 28 28 28 10
```

@kad , do you think this would be accurate enough?

**Comment by askervin** [comment]
Changed the default test topology distances so that nvmem nodes look like being connected to the same memory controllers as numa nodes 0 and 2.
```
$ ssh ubuntu@172.17.4 "$(topology.py bash_topology_dump)" | grep dist
node dist 0: 10 11 21 21 17 28
node dist 1: 11 10 21 21 28 28
node dist 2: 21 21 10 11 28 17
node dist 3: 21 21 11 10 28 28
node dist 4: 17 28 28 28 10 28
node dist 5: 28 28 17 28 28 10
```

**Review by klihub — APPROVED** [review]
LGTM

**Pull request merged**
