### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by marquiz**
Minimal Jenkinsfile for building and pushing container images.

### CODE REVIEW

**Review by klihub — COMMENTED** [review]
I don't know anything about Jenkins. Anybody else can/want to take a look ? @kad, @mythi, @askervin, @ipuustin  ?

**Review by kad — DISMISSED** [review]
lgtm as initial version.

**Comment by klihub** [comment]
@marquiz nit: Do you want to keep that WIP in the commit message ?

**Comment by marquiz** [comment]
Please hold your horses, it's not working, yet (I think) 😄  I just needed to open this for testing the jenkins integration. I'll remove WIP when it is somewhat functional...

**Comment by klihub** [comment]
> Please hold your horses, it's not working, yet (I think)  I just needed to open this for testing the jenkins integration. I'll remove WIP when it is somewhat functional...

Ideally it could have been created as a draft PR in that case. ;-)

**Review by klihub — CHANGES_REQUESTED** [review]
WiP...

**Comment by marquiz** [comment]
> Ideally it could have been created as a draft PR in that case. ;-)

I wasn't sure if Jenkins would pick that up

**Comment by marquiz** [comment]
WIP removed. Good to go from my perspective

**Comment by klihub** [comment]
> > Ideally it could have been created as a draft PR in that case. ;-)
> 
> I wasn't sure if Jenkins would pick that up

Good point. And it also demonstrates my previous comment: I don't know anything about Jenkins. ;-)

**Review by klihub — APPROVED** [review]
It builds. 'nuff said. LGTM.

**Comment by marquiz** [comment]
> And it also demonstrates my previous comment: I don't know anything about Jenkins. ;-)

Well, me neither, that's why I used regular PR 🧐

**Pull request merged**
