### PR TITLE
Support for Ubuntu 24.04

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Review by klihub — APPROVED** [review]

**Review by askervin — APPROVED** [review]
LGTM

**Comment by askervin** [comment]
Approved as it has nothing to do with this patch, either. I'm fine merging this patch and debugging/fixing the issue later.

There is no problem in latest Ubuntu 22.04.

**Comment by klihub** [comment]
> It seems e2e tests fail on Ubuntu 24.04 due to container stop failure. From cri-resmgr.output.txt in vm:
> ```
> E: [resource-manager] StopContainer: failed to stop container pod0:pod0c1: rpc error: code = Unknown desc = failed to stop container "97e4401acd43cba20543030364eb9986d579a886d5c9af5973cda5f2a3a24ae8": unknown
>  error after kill: runc did not terminate successfully: exit status 1: unable to signal init: permission denied
> ```
> 
> I don't know if it has anything to do with cri-resmgr. Fails both topology-aware and balloons tests in the first `kubectl delete pod ...` command.

I'm guessing something SELinux-related, maybe... Probably failure to disable or set to permissive mode during node spinup ?

**Comment by marquiz** [comment]
> I'm guessing something SELinux-related, maybe

Does the latest ubuntu have SELinux enabled?

**Comment by klihub** [comment]
> > I'm guessing something SELinux-related, maybe
> 
> Does the latest ubuntu have SELinux enabled?

Argh... No, sorry, of course it does not. I was still in the context of the previous fedora-related PR I reviewed.

**Review by klihub — APPROVED** [review]

**Pull request merged**
