### PR TITLE
RFC: allow runtime policy switching via agent or forced config file.

### PR DESCRIPTION
**Pull request by klihub**
This patch series adds support for switching policies without shutting down `cri-resmgr`. To allow this to happen, the patch set also reworks/refactors 1) the low-level configuration handling infra, and 2) how options/configuration is passed between the generic policy layer and the policy implementations.

@marquiz @askervin @jukkar @kad @ppalucki PTAL

### CODE REVIEW

**Comment by ppalucki** [comment]
I tested your branch a discovered some issue (I understand this is RFC but just wanted to test some use cases - I'll describe it in another comment).

When applying following configurations by agent:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.default
  namespace: kube-system
data:
  policy: |+
    Active: topology-aware
    ReservedResources:
      CPU: 750m
```
or balloons
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.default
  namespace: kube-system
data:
apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.default
  namespace: kube-system
data:
  policy: |+
    Active: balloons
    AvailableResources:
      CPU: cpuset:1-10
    ReservedResources:
      CPU: cpuset:1
    balloons:
      PinCPU: true
      PinMemory: true
      BalloonTypes:
        - Name: "bal1"
          MinCPUs: 1
          MaxCPUs: 1
          Namespaces:
          - default
          MinBalloons: 1
```
when using those configs with --fallback-config or --force-config it works as expected - so there something between agent/cri-rm and getting info like this `I1103 19:17:11.162052   87921 policy.go:262] starting policy 'topology-aware'...
W`

I got such error from agent:
```
I1103 19:13:52.737138       1 watcher.go:323] group/default ConfigMap updated
I1103 19:13:52.737176       1 watcher.go:245] pushing default configuration to client
I1103 19:13:52.737204       1 config-updater.go:88] scheduling update after 2s rate-limiting timeout...
E1103 19:13:54.740920       1 config-updater.go:105] cri-resmgr configuration error: failed to apply configuration: resource-manager: reverted configuration rejected: resource-manager: reverted configuration: unknown type []uint8

```

and cri-resmgr:
```
I1103 19:13:54.738669   85598 config/server.go:126] SetConfig request: node_name:"kind-control-plane" config:<key:"policy" value:"Active: topology-aware\nReservedResources:\n  CPU: 750m\n" >
I1103 19:13:54.738716   85598 resource-manager/resource-manager.go:223] applying new configuration from agent...
E1103 19:13:54.740538   85598 resource-manager/config.go:112] failed to revert to existing configuration: %!w(*fmt.wrapError=&{resource-manager: reverted configuration rejected: resource-manager: reverted configuration: unknown type []uint8 0xc000c78060})
```
Does the format of configmap/configuration iteself changed? Or I missing something or it is just a bug :) I shouldn't worry yet

**Comment by ppalucki** [comment]
More generic comment- forgive me if it is out of scope of this PR, but I want to give some context.

I tried to just imagine all "failure" cases and how to handle that. The one specific issue that we have is when creating new node in Gardener is: for short period of time, when "infrastructure" pods are being started (including cri-rm), calico/vpn-pod/api-proxy doesn't work yet so agent cannot connect to API server and setup watcher for first 10-30 seconds but it can "sync" config with cri-rm and then what will happen is not obvious - usually the none policy is pushed - ignoring my fallback policy - which is unexpected.

I identified following sources of confusion (races?):
- configmap from agent, or "none" policy if there is missing/not defined,
- built-in or fallback  - depending how cri-rm is deployed,
- cache - depending what happened eariler,
- infrastructure pods starting in unknown order: calico(CNI), vpn, apiproxy, agent and crirm installation, 

Because of this, it becomes hard to predict what end result will be in whole cluster - that depends on the state what happened of the specific node before.

So far we have ugly workaround trying to synchornize agent and cri-rm state by removing cache and restarting cri-rm if we detect that "requested" policy is different from what is currently in use (requested=Cfg.Data.policy vs current=PolicyName). After a while in reconciles to expected state - but in the meantime it requires cri-rm agent to restarts which is not desired.


The proposition bellow is based on assumption, that agent main responsiblity is to deliver configs - I'm ignoring the case that someone wants agent only for adjustments.

 In case we're deploying cri-rm alongside agent such setup will **require** configmaps - and we not allow to fallback config to be set. Then by controlling cri-rm service and agent from the same container - we will wait for agent until it reports readines (there is connection to apiserver, watcher is working and configmap was found) and only then we will start cri-resmgr. It may happen that configmap will be rejected - and then cri-rm should "fallback" nil policy - doing nothing - it is in state that is ready to validate and accept new configs but won't interfere with kublet/container running pods yet. This state is invalid so agent-probe should report issue, best with information what config was rejected.

With such setup, we expect that eventually, after cluster opeartor provides "valid" configurations agent/cri-rm pari synchornize properly.

Cases that need to be handled by agent/cri-rm:
- invalid configmaps (rejected) - agent cannot push to cri-rm,
- missing configmaps - with assumption that configmaps are required, 
- agent cannot connect to api server (setup watcher),
- cri-rm cannot connect to agent,
- pulled configuration by cri-rm is invalid,

cri-rm will use cached policy (which has to be some previous version from agent) but agent probe will fail - and we will mark "this installation" daemonset as unready - that should be sufficient for Gardner to notice that reconcilations of "infrastructure" pods failed.

So there are some changes that I need from cri-rm - mayby not in this PR:
- remove/disable pushing "none" policy from agent,
- allow to configure everyhing (like --mertic-intervals) from configuration,
- agent-probe should fail if any failure cases described above (preferably with some meanigul message)

Probably this PR won't cover everything but I'm putting the info here to give more context - so "swtiching policy" feature to desired state will work regardless cache state and order of /deploying/restart agent and cri-rm and those ugly races.

**Comment by klihub** [comment]
> I tested your branch a discovered some issue (I understand this is RFC but just wanted to test some use cases - I'll describe it in another comment).
> 
> When applying following configurations by agent:
> 
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: cri-resmgr-config.default
>   namespace: kube-system
> data:
>   policy: |+
>     Active: topology-aware
>     ReservedResources:
>       CPU: 750m
> ```
> 
> or balloons
> 
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: cri-resmgr-config.default
>   namespace: kube-system
> data:
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: cri-resmgr-config.default
>   namespace: kube-system
> data:
>   policy: |+
>     Active: balloons
>     AvailableResources:
>       CPU: cpuset:1-10
>     ReservedResources:
>       CPU: cpuset:1
>     balloons:
>       PinCPU: true
>       PinMemory: true
>       BalloonTypes:
>         - Name: "bal1"
>           MinCPUs: 1
>           MaxCPUs: 1
>           Namespaces:
>           - default
>           MinBalloons: 1
> ```
> 
> I got such error from agent:
> 
> ```
> I1103 19:13:52.737138       1 watcher.go:323] group/default ConfigMap updated
> I1103 19:13:52.737176       1 watcher.go:245] pushing default configuration to client
> I1103 19:13:52.737204       1 config-updater.go:88] scheduling update after 2s rate-limiting timeout...
> E1103 19:13:54.740920       1 config-updater.go:105] cri-resmgr configuration error: failed to apply configuration: resource-manager: reverted configuration rejected: resource-manager: reverted configuration: unknown type []uint8
> ```
> 
> and cri-resmgr when it gets setconfig request from agent:
> 
> ```
> I1103 19:13:54.738669   85598 config/server.go:126] SetConfig request: node_name:"kind-control-plane" config:<key:"policy" value:"Active: topology-aware\nReservedResources:\n  CPU: 750m\n" >
> I1103 19:13:54.738716   85598 resource-manager/resource-manager.go:223] applying new configuration from agent...
> E1103 19:13:54.740538   85598 resource-manager/config.go:112] failed to revert to existing configuration: %!w(*fmt.wrapError=&{resource-manager: reverted configuration rejected: resource-manager: reverted configuration: unknown type []uint8 0xc000c78060})
> ```
> 
> or if cri-rm pulls configmap:
> 
> ```
> W1103 23:07:51.745535  204990 config.go:68] failed to load configuration from agent: %!w(*fmt.wrapError=&{resource-manager: failed to load configuration from agent: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string
>  into Go struct field .Policy of type struct { Policy *string "json:\"Active\""; Available *policy.ConstraintSet "json:\"AvailableResources,omitempty\""; Reserved *policy.ConstraintSet "json:\"ReservedResources,omitempty\""; TopologyAware *
> topologyaware.options "`json:\"TopologyAware,omitempty\"`"; Memtier *topologyaware.options "`json:\"Memtier,omitempty\"`"; Balloons *balloons.BalloonsOptions "`json:\"Balloons,omitempty\"`"; Podpools *podpools.PodpoolsOptions "`json:\"Podpo
> ols,omitempty\"`"; Static *static.options "`json:\"Static,omitempty\"`"; StaticPools *stp.config "`json:\"StaticPools,omitempty\"`" } 0xc000127a30})
> ```
> 
> Does the format of configmap/configuration iteself changed? Or I missing something or it is just a bug :) I shouldn't worry yet

The configmap/configuration format has not (been deliberately) changed. However, the way how the full configuration is stitched together from configuration fragments (which are the 'atomic' self-contained pieces of configuration data the various components within cri-resmgr register for themselves in the configuration) has changed. Related to this, also the exact way how the provided configmap data is eventually massaged into the final internal representation has been changed. Maybe that is causing problems. I'll take a look. 
  
> But configs looks fine, when using those configs with --fallback-config or --force-config it works fine..

Hmm..., okay thanks That would suggest the [configMap ->] agent -> cri-resmgr path being broken or the culprit somehow.

> 
> One small question - I want to make sure I deploy proper version of agent but I don't know how to check after it is build (I need build image, load into my kind setup and restart) - To make sure I run latest version is there some way to dump version/build when running cri-resmgr-agent? If not, can you add similar line to what we have in cri-resmgr when starting agent:

> 
> ```
> log.Info("cri-resmgr agent (version %s, build %s) starting...", version.Version, version.Build)
> ```

Yes, we can definitely add it.

**Comment by ppalucki** [comment]
We had discusses what we would expected generally from "switching policy on runtime" and I have additional questions:
- I don't remember how cri-rm behaved previously - but then if some one reset policy and restart cri-rm, do only cached pods switch to new config or all the pods? That leads to a question...
- is it possible to handle  "static pods" (those defined in yamls in kublet/manifests)? - is it possible at all? I cannot drain up node from such pods and reschedule them again - do I need to prepare static/forced config from before even "statics pods" are uploaded to machine?

**Comment by klihub** [comment]
> 
> > But configs looks fine, when using those configs with --fallback-config or --force-config it works fine..
> 
> Hmm..., okay thanks That would suggest the [configMap ->] agent -> cri-resmgr path being broken or the culprit somehow.

Okay, this particular problem (of failing to apply the configuration via the agent) should be fixed now. I forgot that we can't so simply unmarshal the `ConfigMap` data into our configuration because we (need to) use (multiline YAML entries). So we have to jump through an extra hoop, just like we did with the original code.

**Comment by klihub** [comment]
> We had discusses what we would expected generally from "switching policy on runtime" and I have additional questions:
> 
> * I don't remember how cri-rm behaved previously - but then if some one reset policy and restart cri-rm, do only cached pods switch to new config or all the pods? That leads to a question...

All pods (well up to the policy, but)... the policy can't differentiate between pods created from a static manifest and others. So they should/will treat all pods alike.

> * is it possible to handle  "static pods" (those defined in yamls in kublet/manifests)? - is it possible at all? I cannot drain up node from such pods and reschedule them again - do I need to prepare static/forced config from before even "statics pods" are uploaded to machine?

Yes, those should look just like normal pods to cri-resmgr....

**Comment by klihub** [comment]
> One small question - I want to make sure I deploy proper version of agent but I don't know how to check after it is build (I need build image, load into my kind setup and restart) - To make sure I run latest version is there some way to dump version/build when running cri-resmgr-agent? If not, can you add similar line to what we have in cri-resmgr when starting agent:
> 
> ```
> log.Info("cri-resmgr agent (version %s, build %s) starting...", version.Version, version.Build)
> ```

It is possible to ask the agent to dump its version and exit using the `--version` command line option. But I [filed a PR](https://github.com/intel/cri-resource-manager/pull/911) for always dumping the version info on startup.

**Pull request closed without merging**
