### PR TITLE
e2e: add support for k8s=X.Y.Z to set Kubernetes version

### PR DESCRIPTION
**Pull request by askervin**
- Supported initially on ubuntu-* and debian-* distros.
- Update help to include k8s and distro.

### CODE REVIEW

**Comment by askervin** [comment]
This helps answering questions like "does feature X work with k8s version Y".

**Review by klihub — COMMENTED** [review]
@askervin Any plans to add similar support for CentOS, fedora and SUSE ?

**Comment by askervin** [comment]
> Any plans to add similar support for CentOS, fedora and SUSE ?

@klihub, it was very good idea to take a look how would it work. Wasn't too complex after all. All distros are now supported. This only works a bit differently on SUSE: k8s=X.Y.Z and k8s=X.Y.Å will both install X.Y, because only the latest X.Y.* is available through snap.

Rebased.

**Comment by klihub** [comment]
Probably the current snap-based on is cleaner and good enough.

**Review by klihub — APPROVED** [review]

**Pull request merged**
