### PR TITLE
e2e: test dynamic demotion

### PR DESCRIPTION
**Pull request by askervin**
This tests dynamic demotion of heap with lots of small allocations.

### CODE REVIEW

**Comment by askervin** [comment]
RFC: do you agree that sufficient validation could be based on:
- comparing heap page locations of active and passive processes (require that passive is mostly on PMEM while active stays in DRAM)
- reading timestamps and changes in the number of memory pages?

**Comment by klihub** [comment]
> RFC: do you agree that sufficient validation could be based on:
> 
> * comparing heap page locations of active and passive processes (require that passive is mostly on PMEM while active stays in DRAM)
> * reading timestamps and changes in the number of memory pages?

Yes. Sounds like a viable option to me.

**Comment by askervin** [comment]
@klihub, it seems that sometimes cri-resmgr breaks the migration speed limit.

It often seems to happen in the way that pages of some processes are only partly migrated. See below: only few pages of wmrm and wmrn are migrated, and then worm is migrated with full speed. When all processes are summed up, total speed exceeds the limit.

```
round 13 active mem N0=426M N1=356M N2=559M N3=457M N4=0M N5=0M N6=2M N7=0M
round 13 wmrm pid 2515204 VmRSS 2756 kB, pages: N3=542
round 13 worm pid 2503721 VmRSS 2640 kB, pages: N2=540
round 13 wmrn pid 2495632 VmRSS 2760 kB, pages: N1=543
round 13 worn pid 2490259 VmRSS 2640 kB, pages: N0=20 N6=518
validating...
round 14 active mem N0=427M N1=356M N2=558M N3=456M N4=1M N5=0M N6=2M N7=0M
round 14 wmrm pid 2515204 VmRSS 2756 kB, pages: N3=541 N5=1
round 14 worm pid 2503721 VmRSS 2640 kB, pages: N2=340 N4=200
round 14 wmrn pid 2495632 VmRSS 2760 kB, pages: N1=540 N7=3
round 14 worn pid 2490259 VmRSS 2740 kB, pages: N0=20 N6=518
validating...
error: number of PMEM pages grew too quickly on this round
```

Here speed limit is 100 pages/s. Because of inaccuracy of sleep, it is possible that two migration intervals fit in validation round. Thus the test allows twice as much: 200 pages per round. However, here we see 204 pages per round.

**Comment by klihub** [comment]
> @klihub, it seems that sometimes cri-resmgr breaks the migration speed limit.
> 
> It often seems to happen in the way that pages of some processes are only partly migrated. See below: only few pages of wmrm and wmrn are migrated, and then worm is migrated with full speed. When all processes are summed up, total speed exceeds the limit.

> 
> ```
> round 13 active mem N0=426M N1=356M N2=559M N3=457M N4=0M N5=0M N6=2M N7=0M
> round 13 wmrm pid 2515204 VmRSS 2756 kB, pages: N3=542
> round 13 worm pid 2503721 VmRSS 2640 kB, pages: N2=540
> round 13 wmrn pid 2495632 VmRSS 2760 kB, pages: N1=543
> round 13 worn pid 2490259 VmRSS 2640 kB, pages: N0=20 N6=518
> validating...
> round 14 active mem N0=427M N1=356M N2=558M N3=456M N4=1M N5=0M N6=2M N7=0M
> round 14 wmrm pid 2515204 VmRSS 2756 kB, pages: N3=541 N5=1
> round 14 worm pid 2503721 VmRSS 2640 kB, pages: N2=340 N4=200
> round 14 wmrn pid 2495632 VmRSS 2760 kB, pages: N1=540 N7=3
> round 14 worn pid 2490259 VmRSS 2740 kB, pages: N0=20 N6=518
> validating...
> error: number of PMEM pages grew too quickly on this round
> ```
> 
> Here speed limit is 100 pages/s. Because of inaccuracy of sleep, it is possible that two migration intervals fit in validation round. Thus the test allows twice as much: 200 pages per round. However, here we see 204 pages per round.

If by 'limit' you mean the `PageMoveCount` parameter then it is exceeded because it's per process and page
migration is now done in parallel by one dedicated goroutine per target process. In practice this means that
you can't really put a global rate-limit on (the memory bus traffic caused by) page migration. This is the main
reason I wanted to have a 'more user-friendly configuration with rate-limiting'.

**Comment by askervin** [comment]
Thanks, @klihub! I'll change the speed limit calculation so that it is considered realistically per-process limit for now.

**Comment by askervin** [comment]
@klihub , page migration speed is now checked per process.

I think this is now good for real review (no more RFC).

**Review by klihub — COMMENTED** [review]
Wow. This is much more comprehensive than I ever hoped for. Looks good to me.
@marquiz, @kad ?

**Review by klihub — APPROVED** [review]
This still LGTM. @kad, @marquiz ?

**Comment by marquiz** [comment]
lgtm

**Pull request merged**
