### PR TITLE
RELEASE.md: update release process

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Comment by marquiz** [comment]
Just the image repos updated for now. We can capture other needed changes here, too

**Comment by kad** [comment]
@marquiz should it be marked as non-draft? so we can merge it.

**Comment by marquiz** [comment]
> @marquiz should it be marked as non-draft? so we can merge it.

Changed to non-draft. Does the documented release process resonate with reality, still after v0.4.0? 😉

**Review by klihub — APPROVED** [review]
If there are no further updates for now, I'd suggest merging these ones.

**Pull request merged**
