### PR TITLE
e2e: podpools metrics test

### PR DESCRIPTION
**Pull request by askervin**
This patch implements end-to-end test for PR #692.

Prerequisites:
- docker
- govm

How to install prerequisites on Ubuntu and Debian:
```
sudo apt install -y docker.io git-core golang
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
GO111MODULE=off go get -d github.com/govm-project/govm && cd $GOPATH/src/github.com/govm-project/govm && go mod tidy && go mod download && go install && cd .. && docker build govm -f govm/Dockerfile -t govm/govm:latest
```

Usage:

```
test/e2e$ ./run_tests.sh policies.test-suite/podpools/n4c16/test06-prometheus-metrics
```

### CODE REVIEW

**Comment by huangrui666** [comment]
Hi Antti, I have tried this test aiming to verify my new patch. But when I run the command:
./run_tests.sh policies.test-suite/podpools/n4c16/test06-prometheus-metrics
The container keep restarting and the log is:
**Failed to open module: Error relocating /usr/bin/../lib/qemu/hw-display-qxl.so: qemu_spice_display_switch: symbol not found**
Do you have any ideas?

**Comment by askervin** [comment]
@huangrui666, it sounds like there is something wrong with the govm Docker image. Maybe a glitch in alpine-based image dependencies and library versions.

I just fetched the latest govm project, deleted old govm images and built new govm image without cache to see if I could reproduce the issue:

```
docker build --no-cache govm -f govm/Dockerfile -t govm/govm:latest
```

Qemu runs fine inside that image. I would recommend you to do the same. If the problem persists, would you try what this prints to you:

```
$ docker run -it govm/govm:latest bash
bash-5.1# ls -l /usr/bin/qemu-system-x86_64 /usr/lib/qemu/ui-opengl.so /usr/lib/qemu/ui-spice-core.so
-rwxr-xr-x    1 root     root      18067736 Jun 10 13:57 /usr/bin/qemu-system-x86_64
-rwxr-xr-x    1 root     root         30944 Jun 10 13:57 /usr/lib/qemu/ui-opengl.so
-rwxr-xr-x    1 root     root         64808 Jun 10 13:57 /usr/lib/qemu/ui-spice-core.so
bash-5.1# md5sum /usr/bin/qemu-system-x86_64 /usr/lib/qemu/ui-opengl.so /usr/lib/qemu/ui-spice-core.so
5f6cd65cb9e652feb49c3f59cb90894b  /usr/bin/qemu-system-x86_64
eb594df412879ec8b629671b9f8f4044  /usr/lib/qemu/ui-opengl.so
1e26c5500e5fbfdb9175eeb68de6a896  /usr/lib/qemu/ui-spice-core.so
bash-5.1# LD_PRELOAD="/usr/bin/qemu-system-x86_64 /usr/lib/qemu/ui-opengl.so /usr/lib/qemu/ui-spice-core.so" ldd /usr/lib/qemu/hw-display-qxl.so
```
The last command doesn't report any missing libraries or symbols on my govm image.

**Comment by askervin** [comment]
@huangrui666, now that podpools metrics is merged, I think we should have a test for it.

This test verifies that reported CPUs for each container are correct, and that CPU usage is in expected range. However, it does not do any syntax check for metrics output lines.

Would you like to add/change/remove something for this test, or should we start regular podpools metrics validation with this?

**Review by klihub — COMMENTED** [review]
LGTM. I'd be ready to merge this as a start if @huangrui666 also considers this to be good enough.

**Comment by huangrui666** [comment]
hi @askervin, I think maybe it's better to add some syntax check for metrics output, especially labels like container_name or pod_name which is the combination of different names. For example:
`pool_cpu_usage{CPUs="8-9",container_name="**pod3:pod3c0**,pod3:pod3c1,pod3:pod3c2,pod3:pod3c3",def_name="400mCPU",memory="2",pod_name="pod3",policy="podpools",pool_size="2000",pretty_name="400mCPU[3]"} 31.5136476426799

pool_cpu_usage{CPUs="8-9",container_name="pod3:pod3c1,pod3:pod3c2,pod3:pod3c3,**pod3:pod3c0**",def_name="400mCPU",memory="2",pod_name="pod3",policy="podpools",pool_size="2000",pretty_name="400mCPU[3]"} 31.5136476426799`

These metrics will be considered 2 different metrics because the container_name has different container name order.

**Comment by askervin** [comment]
@huangrui666 , thanks for your comments!

I implemented syntax check by adding [verify-metrics-has-line REGEXP](https://github.com/askervin/cri-resource-manager/blob/5EG_podpools_metrics/test/e2e/policies.test-suite/podpools/n4c16/test06-prometheus-metrics/code.var.sh#L72)  check to a pod with four containers. This checks that the order in which pretty container names are listed is exactly what is expected. Using regexp instead of exact match leaves still freedom for podpools to assing this container to another valid pool. So hopefully this test won't give false negative result too soon.

Do you think this would be sufficient addition for merging the test, or would you like to see something else, too?

**Comment by huangrui666** [comment]
Hi @askervin, it looks good to me. Thank you for your filing test cases for this feature!

**Review by klihub — APPROVED** [review]
LGTM

**Pull request merged**
