### PR TITLE
balloons: improve dynamic configuration update

### PR DESCRIPTION
**Pull request by askervin**
- Recreate balloons and reassign workloads only if necessary.
- CPU class of balloon types can be switched without reassigning
  workloads.

### CODE REVIEW

**Review by klihub — CHANGES_REQUESTED** [review]
@askervin This needs a few minor touches to make `gofmt` happy.

**Comment by askervin** [comment]
> @askervin This needs a few minor touches to make `gofmt` happy.

I don't get `gofmt` complaints, and reformatting every file does not change anything... Let's see if our environments differ...

**Comment by klihub** [comment]
> > @askervin This needs a few minor touches to make `gofmt` happy.
> 
> I don't get `gofmt` complaints, and reformatting every file does not change anything... Let's see if our environments differ...

In this case you don't even need to check it locally, there are only a very few related to `for i := ` being preferred over `for i, _ := `. You can check the [logs for the failed verify workflow](https://github.com/intel/cri-resource-manager/runs/6875356685?check_suite_focus=true).

**Comment by klihub** [comment]
And here is another patch I had to roll to fix up the unit tests:
[0001-balloons-adjust-unit-tests-for-update-option-types.patch.gz](https://github.com/intel/cri-resource-manager/files/8926251/0001-balloons-adjust-unit-tests-for-update-option-types.patch.gz)
.

**Comment by askervin** [comment]
Wow, thanks @klihub
gofmt should be now happy. Applied your unit test fix as a separate commit in this PR.

**Review by klihub — APPROVED** [review]
LGTM

**Pull request merged**
