### PR TITLE
memtier: add multi-die topology support.

### PR DESCRIPTION
**Pull request by klihub**
Add topology support for physical packages with multiple dies. On multi-die systems the topology tree will
have additional nodes/pools representing dies. On a multi-socket system with multiple dies per socket the
full topology hierarchy is `root->socket->die->NUMA node` with `SNC` enabled. Consequently, allocations
not fitting into a single NUMA node will spill to the parent die before the socket.

### CODE REVIEW

**Comment by klihub** [comment]
@askervin This could be ripe now for review.

**Comment by askervin** [comment]
I'm testing in `test/numa` VM with topology:
```
topology='[
    {"mem": "1G", "cores": 1, "nodes": 2, "dies": 2, "packages": 2},
    {"nvmem": "8G", "node-dist": {"0": 17}},
    {"nvmem": "8G", "node-dist": {"2": 17}}
    ]' ./run.sh interactive
```

This results in 8 nodes with a CPU (nodes 0-7), and two CPU-less PMEM NUMA nodes (id's 8 and 9) that are connected to the same memory controllers as NUMA nodes 0 and 2.

Let's create a guaranteed pod (`pod0`) that requires 3 CPUs and 1G of mem:
```
run.sh> CPU=3 MEM=1G create guaranteed
```

Then let's visualize how OS sees the pod. Printing `Cpus_allowed` and `Mems_allowed` using [coming res_allowed patch](https://github.com/askervin/cri-resource-manager/tree/58M_e2e_mem_allowed), that visualizes mem-only NUMA nodes in CPU tree under nodes that share the same memory controller.
```
ubuntu@crirm-test-numa:~$ ./topology.py res_allowed pod0
package0 die0 node0 core0 thread0 cpu00 pod0-113986
                          thread1 cpu01 pod0-113986
                    mem0  --      mem1G pod0-113986
                    mem8  --      mem8G pod0-113986
              node1 core1 thread0 cpu02 pod0-113986
                          thread1 cpu03
                    mem1  --      mem1G pod0-113986
         die1 node2 core0 thread0 cpu04
                          thread1 cpu05
                    mem2  --      mem1G
                    mem9  --      mem8G
              node3 core1 thread0 cpu06
                          thread1 cpu07
                    mem3  --      mem1G
package1 die0 node4 core0 thread0 cpu08
                          thread1 cpu09
                    mem4  --      mem1G
              node5 core1 thread0 cpu10
                          thread1 cpu11
                    mem5  --      mem1G
         die1 node6 core0 thread0 cpu12
                          thread1 cpu13
                    mem6  --      mem1G
              node7 core1 thread0 cpu14
                          thread1 cpu15
                    mem7  --      mem1G
```

That is, allocations have been made on socket0/die0. At this point `cri-resmgr` has printed:
```
- children:
  <socket #0>
    - node CPU: <socket #0 CPU: sharable:0-7 (granted:0, free: 8000), Mem: limit: { pmem:16885129216, dram: 4157603840}, granted: { pmem:0, dram: 0}>
    - free CPU: <socket #0 CPU: sharable:0-7 (granted:0, free: 8000), Mem: limit: { pmem:16885129216, dram: 4157603840}, granted: { pmem:0, dram: 0}>
    - children:
      <die #0/0>
        - node CPU: <die #0/0 CPU: sharable:0-3 (granted:0, free: 4000), Mem: limit: { pmem:8455536640, dram: 2112184320}, granted: { pmem:0, dram: 0}>
        - free CPU: <die #0/0 CPU: sharable:3 (granted:0, free:1000), Mem: limit: { pmem:7455536640, dram: 2112184320}, granted: { pmem:1000000000, dram: 0}>
        - PMEM memory: 8
          + <CPU grant for pod0:busybox from die #0/0: exclusive: 0-2, mem: mem limit: { pmem: 1000000000, dram: 0 }>
        - parent: <socket #0>
        - children:
          <NUMA node #0>
            - node CPU: <numa node #0 CPU: sharable:0-1 (granted:0, free: 2000), Mem: limit: { pmem:8455536640, dram: 1055842304}, granted: { pmem:0, dram: 0}>
            - free CPU: <numa node #0 CPU: -, Mem: limit: { pmem:8455536640, dram: 1055842304}, granted: { pmem:0, dram: 0}>
          <NUMA node #1>
            - node CPU: <numa node #1 CPU: sharable:2-3 (granted:0, free: 2000), Mem: limit: { pmem:0, dram: 1056342016}, granted: { pmem:0, dram: 0}>
            - free CPU: <numa node #1 CPU: sharable:3 (granted:0, free: 1000), Mem: limit: { pmem:0, dram: 1056342016}, granted: { pmem:0, dram: 0}>
```

Now comparing `node CPU` and `free CPU` lines under `die #0/0` shows that something has been consumed (3000 mCPUs).

Question: should corresponding lines on the parent node (`<socket #0>`) reflect the same thing?

**Comment by klihub** [comment]
> Now comparing `node CPU` and `free CPU` lines under `die #0/0` shows that something has been consumed (3000 mCPUs).
> 
> Question: should corresponding lines on the parent node (`<socket #0>`) reflect the same thing?

Hmm... the node dumps only account for containers directly assigned to the node itself, omitting those assigned lower in its subtree. Arguably this is misleading at best incorrect at worst. I'll look into it.

**Review by askervin — APPROVED** [review]
Test in a topology where die nodes are leaf nodes. Looks good:
```
topology='[{"threads":1,"cores":1,"nodes":1,"dies":2,"mem":"4G"}]' \
code='CPU=1200m create guaranteed; report cpus; delete pods --all --now; CPU=400m n=3 create guaranteed; report cpus' \
./run.sh test
...
Pod   Cpus_allowed_mask
pod0  11
...
Pod   Cpus_allowed_mask
pod1  01
pod2  10
pod3  01
```

Tested in a topology with 2 dies/socket, 8 CPUs per die. Verify how dies in the topology tree are filled. (Testing with demo/lib/topology.py from PR #367 copied on the VM.) Looks good:
```
vm=c32d4p2 \
topology='[{"threads":2,"cores":2,"nodes":2,"dies":2,"packages":2,"mem":"1G"}]' \
code='CPU=5 n=3 create guaranteed; vm-command "./topology.py res_allowed pod0 pod1 pod2"; interactive' \
./run.sh test

root@vm> ./topology.py res_allowed pod0 pod1 pod2                                                                                                                                                           package0 die0 node0 core0 thread0 cpu00 pod0-21755
                          thread1 cpu01 pod0-21755
                    core1 thread0 cpu02 pod0-21755
                          thread1 cpu03 pod0-21755
                    mem   node0   1G    pod0-21755
              node1 core2 thread0 cpu04 pod0-21755
                          thread1 cpu05
                    core3 thread0 cpu06
                          thread1 cpu07
                    mem   node1   1G    pod0-21755
         die1 node2 core0 thread0 cpu08 pod1-22269
                          thread1 cpu09 pod1-22269
                    core1 thread0 cpu10 pod1-22269
                          thread1 cpu11 pod1-22269
                    mem   node2   1G    pod1-22269
              node3 core2 thread0 cpu12 pod1-22269
                          thread1 cpu13
                    core3 thread0 cpu14
                          thread1 cpu15
                    mem   node3   1G    pod1-22269
package1 die0 node4 core0 thread0 cpu16 pod2-22763
                          thread1 cpu17 pod2-22763
                    core1 thread0 cpu18 pod2-22763
                          thread1 cpu19 pod2-22763
                    mem   node4   1G    pod2-22763
              node5 core2 thread0 cpu20 pod2-22763
                          thread1 cpu21
                    core3 thread0 cpu22
                          thread1 cpu23
                    mem   node5   1G    pod2-22763
         die1 node6 core0 thread0 cpu24
                          thread1 cpu25
                    core1 thread0 cpu26
                          thread1 cpu27
                    mem   node6   1G
              node7 core2 thread0 cpu28
                          thread1 cpu29
                    core3 thread0 cpu30
                          thread1 cpu31
                    mem   node7   1G
```

**Pull request merged**
