### PR TITLE
control/rdt: fix discovery of pod qos classes in discovery mode

### PR DESCRIPTION
**Pull request by marquiz**
Search RDT classes based on their name, not based on their index in our internal array. Also, update code comments.

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]
Verified that this fixes the linter error.

**Comment by marquiz** [comment]
Hmm, hold on, do not merge this yet

**Review by askervin — APPROVED** [review]
LGTM

**Comment by marquiz** [comment]
Now ready for review. Updated some code comments

**Review by klihub — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]

**Review by askervin — APPROVED** [review]
LGTM

**Pull request merged**
