### PR TITLE
e2e: detect cri-resmgr(-agent) with fuser/pidfile instead of pidof

### PR DESCRIPTION
**Pull request by askervin**
- pidof cri-resmgr does not work when cri-resmgr runs with custom
  glibc versions.

### CODE REVIEW

**Comment by askervin** [comment]
Marking this as draft, because this should be aligned with "cri-resmgr as NRI plugin usecase". What would be the best routine to find out the PID of cri-resmgr and signal (kill) it in all cases?

**Comment by klihub** [comment]
> Marking this as draft, because this should be aligned with "cri-resmgr as NRI plugin usecase". What would be the best routine to find out the PID of cri-resmgr and signal (kill) it in all cases?

We could change it to write a pid-file under `/run/cri-resmgr` once it has taken the socket... We could even have it register a simple gRPC-protocol of its own with a `Shutdown()` (and anything else we might see fit)  and the corresponding command line option `--shutdown` which would connect to the socket and do the gRPC `Shutdown()` client call. I don't know what would be the best.

**Comment by marquiz** [comment]
A pid file wounds sounds like an easy-ish "standard" solution to me

**Comment by askervin** [comment]
Good, sounds like a pid file then. :)

Opinions, shall I close this PR, or should we keep it in the list as a reminder. In the latter case I'll update this with s/fuser/pidfile when we have it.

**Review by klihub — APPROVED** [review]
LGTM

**Pull request merged**
