### PR TITLE
[backport from nri-plugins] all: stop importing kubernetes/kubelet internals.

### PR DESCRIPTION
**Pull request by klihub**
Stop importing kubernetes/kubelet internals.

Instead of importing cpuset.CPUSet directly from the kubelet, switch to using k8s.io/utils/cpuset. However, don't import it directly all over the map. Instead wrap it in a single place (pkg/utils/cpuset) and import it everywhere else from there.

Instead of importing kubernetes/kubelet for namespace, label, and milli-CPU conversion constants and functions
define our own constants and functions for those few stable things we need.

Eliminating these two dependencies greatly reduces the kubernetes blast radius in the code base. The offending files before and after these commits are:

```
# before:
klitkey1-mobl1 switch-to-k8sio-utils-cpuset $ git grep 'k8s.io/kubernetes/' HEAD^ -- '*.go' | sed 's/HEAD^://g;s/:.*$//g' | sort -u
pkg/cpuallocator/allocator.go
pkg/cpuallocator/cpuallocator_test.go
pkg/cri/resource-manager/cache/cache.go
pkg/cri/resource-manager/cache/cache_test.go
pkg/cri/resource-manager/cache/utils.go
pkg/cri/resource-manager/control/cpu/cpu.go
pkg/cri/resource-manager/kubernetes/cpuset.go
pkg/cri/resource-manager/kubernetes/cpuset_test.go
pkg/cri/resource-manager/kubernetes/kubernetes.go
pkg/cri/resource-manager/policy/builtin/balloons/balloons-policy.go
pkg/cri/resource-manager/policy/builtin/balloons/cputree.go
pkg/cri/resource-manager/policy/builtin/balloons/cputree_test.go
pkg/cri/resource-manager/policy/builtin/balloons/metrics.go
pkg/cri/resource-manager/policy/builtin/dynamic-pools/dyp.go
pkg/cri/resource-manager/policy/builtin/dynamic-pools/dyp_test.go
pkg/cri/resource-manager/policy/builtin/dynamic-pools/metrics.go
pkg/cri/resource-manager/policy/builtin/podpools/metrics.go
pkg/cri/resource-manager/policy/builtin/podpools/podpools-policy.go
pkg/cri/resource-manager/policy/builtin/podpools/podpools-policy_test.go
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go
pkg/cri/resource-manager/policy/builtin/static/static-policy.go
pkg/cri/resource-manager/policy/builtin/topology-aware/cache.go
pkg/cri/resource-manager/policy/builtin/topology-aware/cache_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/hint.go
pkg/cri/resource-manager/policy/builtin/topology-aware/hint_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/mocks_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/node.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools.go
pkg/cri/resource-manager/policy/builtin/topology-aware/pools_test.go
pkg/cri/resource-manager/policy/builtin/topology-aware/resources.go
pkg/cri/resource-manager/policy/builtin/topology-aware/topology-aware-policy.go
pkg/cri/resource-manager/policy/flags.go
pkg/cri/resource-manager/policy/policy.go
pkg/sysfs/system.go
pkg/sysfs/utils.go
test/functional/e2e_test.go
``` 

and

```
# after:
klitkey1-mobl1 switch-to-k8sio-utils-cpuset $ git grep 'k8s.io/kubernetes/' '*.go' 
pkg/cri/resource-manager/policy/builtin/static-plus/static-plus-policy.go://    code (from k8s.io/kubernetes/pkg/kubelet/cm/helpers_linux.go).
```

Same through go.mod and go.sum:

```
klitkey1-mobl1 switch-to-k8sio-utils-cpuset $ git grep k8s.io/ HEAD^^ -- go.mod go.sum | wc -l
85
klitkey1-mobl1 switch-to-k8sio-utils-cpuset $ git grep k8s.io/ HEAD -- go.mod go.sum | wc -l
36
```

### CODE REVIEW

**Review by jukkar — DISMISSED** [review]

**Review by askervin — APPROVED** [review]
LGTM.
For a little while I was pondering regarding the copyright being NRI Plugins authors, but as this is a backport, I suppose that's fine, too.

**Comment by marquiz** [comment]
I like this. But needs rebase

**Review by marquiz — DISMISSED** [review]
LGTM

**Review by marquiz — APPROVED** [review]
LGTM

**Review by marquiz — APPROVED** [review]

**Comment by marquiz** [comment]
ping @askervin @kad

**Pull request merged**
