### PR TITLE
Documentation reorg

### PR DESCRIPTION
**Pull request by marquiz**
Major overhaul of the layout of documentation, both on file level and in html layout. This PR tries to pave way for future documentation improvements, making it easier to understand *what* pieces are missing and *where* to add new pieces.

One leading thought was to try to keep the `docs/` directory as self-contained as possible, trying to keep all documentation files it.

Additions to the actual content are rather minor at this point.

The PR currently consists of numerous patches to better understand what is being changed and how.

### CODE REVIEW

**Comment by marquiz** [comment]
Output looks like this:
https://marquiz.github.io/cri-resource-manager

**Review by klihub — APPROVED** [review]
LRGTM. IMO the outlined structure looks much much saner than the old one. I'm all in on this one.

**Comment by marquiz** [comment]
Removed the draft status. Any comments from others: @mythi @kad @askervin ?

If this looks sane I would merge this sooner than later as maintaining the reorg in a separate branch is tedious and error prone if/when the documentation on the master branch evolves.

**Comment by klihub** [comment]
Argh... I hugged up when merging this. Forgot to squash history. I wish github had an option for creating the PR so that the merge would automatically defaulto to squashing. I think this PR was a prime example when that would be extremely useful. Plus it would indicate to reviewers that the detailed history is only there to help an iterative review process and not to be included in the final merged history.

**Comment by marquiz** [comment]
Well, I could've squashed it myself 😬  A bit of noise in the repo but no big harm done

**Pull request merged**
