### PR TITLE
docs: update the govm setup instructions

### PR DESCRIPTION
**Pull request by marquiz**
We're not compatible with the latest govm.

### CODE REVIEW

**Comment by marquiz** [comment]
After fighting with this on a fresh dev machine I decided to update the docs...

**Review by klihub — APPROVED** [review]

**Comment by klihub** [comment]
I again mixed up PR. My following comment the other day was about this PR, so I repeat it here:

It is [this commit]( https://github.com/govm-project/govm/commit/f4dd720278d7fe345ed13347646a270c8edf23a9) which breaks govm for us.

**Review by askervin — APPROVED** [review]
LGTM.

**Comment by marquiz** [comment]
ping @askervin @klihub

**Comment by klihub** [comment]
> ping @askervin @klihub

I'm fine with this if we get the lost job running and the CI test to pass so we can merge this.

**Pull request merged**
