### PR TITLE
demo/lib: add basic environment checks for govm.

### PR DESCRIPTION
**Pull request by klihub**

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
lgtm

**Review by askervin — CHANGES_REQUESTED** [review]
govm uses qemu from its docker image. It does not depend on qemu installed on system.

**Comment by klihub** [comment]
> govm uses qemu from its docker image. It does not depend on qemu installed on system.

Ah, good point. I'll update.

**Review by askervin — APPROVED** [review]
LGTM

**Pull request merged**
