### PR TITLE
switch to building against kubernetes v1.17.2

### PR DESCRIPTION
**Pull request by klihub**

### CODE REVIEW

**Comment by marquiz** [comment]
Hmm, there seems to be some unrelated stuff like mangling cri-rm startup

**Comment by klihub** [comment]
> Hmm, there seems to be some unrelated stuff like mangling cri-rm startup

Yes, I known what it is. It's the test cases triggering our unsafe (racy) using logging vs. reconfiguring logging.

**Comment by mythi** [comment]
FWIW, in device-plugins we started to run `go mod tidy` check to make sure the PR includes the necessary cleanups too. Would that make sense here too?

https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/Makefile#L25

**Comment by klihub** [comment]
> FWIW, in device-plugins we started to run `go mod tidy` check to make sure the PR includes the necessary cleanups too. Would that make sense here too?
> 
> https://github.com/intel/intel-device-plugins-for-kubernetes/blob/master/Makefile#L25

Sure, I'm, fine with that. Someone just needs to add it to the Makefile and file a PR for it.

**Comment by mythi** [comment]
> Sure, I'm, fine with that. Someone just needs to add it to the Makefile and file a PR for it.

the implicit question was did you run it before this PR? :)

**Comment by klihub** [comment]
> > Sure, I'm, fine with that. Someone just needs to add it to the Makefile and file a PR for it.
> 
> the implicit question was did you run it before this PR? :)

Yes. But then I saw that many of the changes it made to go.mod and go.sum were related to mistakes (of not running) in connection with other PRs, so I reverted. But maybe it's a good idea to have it here, since we're touching dependencies heavy-handedly. I'll add a separate commit doing it to this PR.

**Comment by mythi** [comment]
rebase + add the missing fixes

**Comment by klihub** [comment]
Closing temporarily. Will rebase onto #168 .

**Pull request closed without merging**
