### PR TITLE
balloons: add sharedidlecpus and balloon topology to metrics

### PR DESCRIPTION
**Pull request by askervin**
This PR depends on and includes commits from PR #946.

This PR is part of the series that replaces PR #931.

### CODE REVIEW

**Review by klihub — APPROVED** [review]
@marquiz @fmuyassarov @jukkar LGTM. If you guys have BW to take a better/closer look, please do so.

**Review by jukkar — APPROVED** [review]
LGTM

**Review by marquiz — DISMISSED** [review]
Thanks @askervin 👍 Looks good to me. Let's get this rebased and merged after all the dependencies are merged

**Comment by askervin** [comment]
Rebased on top of updated #946 .

**Review by klihub — APPROVED** [review]
LGTM.

**Review by marquiz — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]

**Pull request merged**
