### PR TITLE
.gitignore: updates, add patterns for packaging artifacts.

### PR DESCRIPTION
**Pull request by klihub**

### CODE REVIEW

**Review by askervin — APPROVED** [review]
LGTM.

A bonus would be ignoring `make e2e-test` output files:
```
__pycache__
/test/**/output
```

**Comment by klihub** [comment]
> LGTM.
> 
> A bonus would be ignoring `make e2e-test` output files:
> 
> ```
> __pycache__
> /test/**/output
> ```

Good point. I'll add those.

**Review by marquiz — APPROVED** [review]
lgtm

**Review by kad — APPROVED** [review]
lgtm

**Pull request merged**
