### PR TITLE
docs: fix internal refs in architecture.md

### PR DESCRIPTION
**Pull request by marquiz**
Make documentation buildable, again.

### CODE REVIEW

**Review by klihub — APPROVED** [review]
What the hug ? This is exactly what I tried first before settling for [../]../pkg in the original PR. And it did not work. Maybe I had some lysdexic typo there. Anyway, LGTM.

**Comment by marquiz** [comment]
Don't merge just yet. Seems that the figures are somehow not showing....

**Comment by klihub** [comment]
> Don't merge just yet. Seems that the figures are somehow not showing....

Argh... too late now.

**Comment by klihub** [comment]
> Don't merge just yet. Seems that the figures are somehow not showing....

My guess is sphinx can't properly handle links in HTML snippets directly embedded into markdown.

**Comment by marquiz** [comment]
Seems that the site is fine. I had some local problem

**Pull request merged**
