### PR TITLE
[release-0.6] docs: Fix doc and example config typos/indentation

### PR DESCRIPTION
**Pull request by marquiz**
* fix indentation
  (cherry picked from commit 4f0be74a53e3ce460709aed25b02f9e3eb7887c1)
* fix typos, indentation etc.
  (cherry picked from commit 706aa60f02a935ad92f4a6cd3aa28c92d81e0427)

### CODE REVIEW

**Review by klihub — COMMENTED** [review]
Those fixes LGTM.

The build error is a bit strange. I couldn't reproduce it on my development or test machines (although neither are clean and both have golang 1.17.6).

Additionally, looking at the protoc and vfsgendev actions, I think we have insufficiently defined/locked down dependencies. Pulling in protoc updates grpc, and pulling vfsgendev gets a newer version.

**Comment by marquiz** [comment]
> The build error is a bit strange. I couldn't reproduce it on my development or test machines (although neither are clean and both have golang 1.17.6).

Yeah, really strange 🧐 Need to try with golang 1.16 locally (I currently have only v1.17, too)
 
> Additionally, looking at the protoc and vfsgendev actions, I think we have insufficiently defined/locked down dependencies. Pulling in protoc updates grpc, and pulling vfsgendev gets a newer version.

Good point. Those versions should be fixed

**Review by askervin — DISMISSED** [review]
LGTM.

(Reviewed yaml indentation in emacs after all... browser made it look suspicious, but l3schema and mbschema were in the same depth after all...)

**Comment by marquiz** [comment]
rebased, ping @jukkar @askervin

**Review by jukkar — APPROVED** [review]

**Pull request merged**
