### PR TITLE
Bump builds to use Golang v1.20.2

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Review by klihub — DISMISSED** [review]

**Review by fmuyassarov — DISMISSED** [review]
LGTM

**Comment by marquiz** [comment]
Pick either this or #981 😉

**Review by jukkar — APPROVED** [review]
I am fine with both versions.

**Comment by klihub** [comment]
Marked as draft. Let's keep this ready in the back pocket until we're more confident to switch to 1.20.

**Comment by marquiz** [comment]
We chose #981

**Comment by marquiz** [comment]
Rebased

**Comment by marquiz** [comment]
Updated to v1.20.2. Moved out of dfaft state. Ping @klihub

**Review by klihub — APPROVED** [review]

**Pull request merged**
