### PR TITLE
deps: update dependencies to k8s 1.23.3.

### PR DESCRIPTION
**Pull request by klihub**

### CODE REVIEW

**Review by marquiz — APPROVED** [review]
Let's merge.

One optional suggestion, though. We could update directly to v1.23.3 which is the latest afaiu.

On a sidenote we should really drop circleci...

**Comment by klihub** [comment]
> Let's merge.
> 
> One optional suggestion, though. We could update directly to v1.23.3 which is the latest afaiu.

Ok, let me check if updating there goes nice and easy and if it does we can jump directly there...

> On a sidenote we should really drop circleci...

I'm fine with dropping circleci... @kad WDYT ?

**Review by jukkar — APPROVED** [review]

**Comment by klihub** [comment]
@marquiz Updated deps to 1.23.3. If CI tests pass, PTAL...

**Review by marquiz — APPROVED** [review]
👍  LGTM

**Pull request merged**
