### PR TITLE
test/e2e: update packaging tests

### PR DESCRIPTION
**Pull request by marquiz**

### CODE REVIEW

**Review by jukkar — COMMENTED** [review]
Please add some description to both commit messages **why** the change is needed. Now it is unclear why the change is done.

**Review by askervin — DISMISSED** [review]
LGTM.

demo/lib/distro.bash does not have support for opensuse-15.4 yet, though. As a result, this packaging test will currently run on opensuse-15.3. 

I tried out adding it:
```
opensuse-image-url() {
    opensuse-15_4-image-url
}

opensuse-15_4-image-url() {
    echo "https://download.opensuse.org/pub/opensuse/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-JeOS.x86_64-15.4-OpenStack-Cloud-Current.qcow2"
}
```

However, Qemu seems to be stuck in boot-loop. This can be addressed in later commits, anyway.

**Comment by marquiz** [comment]
> Please add some description to both commit messages **why** the change is needed. Now it is unclear why the change is done.

Added reasoning to the commit messages

**Review by jukkar — DISMISSED** [review]

**Comment by askervin** [comment]
@marquiz, after debugging this it seems that opensuse 15.4 boots when qemu gets -vga qxl, but has issues with -nographics. Reverting commit c2f3ff80fd14653b8f5bad07fc5c860156df74ff enabled booting it.

This commit can be merged as is, and 15.4 issue fixed separately.

**Review by klihub — APPROVED** [review]
LGTM.

**Review by jukkar — APPROVED** [review]

**Comment by marquiz** [comment]
ping @askervin @jukkar should we merge this? I verified that now the tests actually pass

**Review by askervin — APPROVED** [review]
LGTM.

**Pull request merged**
