### PR TITLE
build: add rule for building binary dist tarballs.

### PR DESCRIPTION
**Pull request by klihub**

### CODE REVIEW

**Review by askervin — COMMENTED** [review]
binary-dist tarball includes binaries under `/opt/intel/bin`, but `/etc/systemd/system/cri-resource-manager.service` in the package wants to run `/usr/bin/cri-resmgr`. Perhaps we'd like to use the same `PREFIX` there as well.

**Comment by klihub** [comment]
> binary-dist tarball includes binaries under `/opt/intel/bin`, but `/etc/systemd/system/cri-resource-manager.service` in the package wants to run `/usr/bin/cri-resmgr`. Perhaps we'd like to use the same `PREFIX` there as well.

Ah, thanks for spotting that. I missed it altogether.

**Review by kad — APPROVED** [review]
lgtm

**Review by askervin — APPROVED** [review]
LGTM

Tested manually by unpacking to Ubuntu 20.04 rootfs and launching with `systemctl`. Started up nicely after `mv /etc/cri-resmgr/fallback.cfg.sample /etc/cri-resmgr/fallback.cfg`. And I believe this is how it is supposed to be.

**Pull request merged**
