### PR TITLE
agent: implement config status readiness probe.

### PR DESCRIPTION
**Pull request by klihub**
Implement propagating the status of the last configuration update back to the control plane via the agent, the agent probe and a deployment readiness probe.

### CODE REVIEW

**Comment by klihub** [comment]
@marquiz Let's iron out anything that you guys think needs addressing/fixing in this PR. Once we're happy and merge this, I can file another version of this PR (plus #985) rebased on top of the release-0.8 branch.

**Review by fmuyassarov — COMMENTED** [review]
LGTM

**Review by askervin — COMMENTED** [review]
All changes look good to me.

Would also you update `pkg/cri/resource-manager/resource-manager.go:loadConfig()` documentation to match new, agent.GetConfig()-less start-up sequence?

**Comment by klihub** [comment]
> All changes look good to me.
> 
> Would also you update `pkg/cri/resource-manager/resource-manager.go:loadConfig()` documentation to match new, agent.GetConfig()-less start-up sequence?

Ah, yes. I'll update. Thanks for spotting that. Should have had `GetConfig()` mentioned in the comment that was warning about `GetConfig()` becoming a problem once we implement error propagation.

**Comment by marquiz** [comment]
I think codewise this looks good. It's just a bit funny to piggy-back on the agent pods Ready condition to reflect the status of the main cri-resmgr. I'd at least suggest to document this clearly, in the deployment yaml (I don't know if somewhere else) what we're doing, i.e. Ready doesn't relfect readiness of the agent but the main daemon which is running somewhere else

**Comment by klihub** [comment]
> I think codewise this looks good. It's just a bit funny to piggy-back on the agent pods Ready condition to reflect the status of the main cri-resmgr. I'd at least suggest to document this clearly, in the deployment yaml (I don't know if somewhere else) what we're doing, i.e. Ready doesn't relfect readiness of the agent but the main daemon which is running somewhere else

I know. This was explicitly asked from us by the polish team, I guess so they could build some tooling on top, maybe to monitor readiness and automatically fetch errors from the agent's log. I'll add a big fat comment about it to the deployment file.

**Comment by marquiz** [comment]
> I know. This was explicitly asked from us by the polish team, I guess so they could build some tooling on top, maybe to monitor readiness and automatically fetch errors from the agent's log. I'll add a big fat comment about it to the deployment file.

Yeah, I understand this, and I think it's fine. But better to document that we're doing some special trickery here. Thx

**Comment by klihub** [comment]
> > I know. This was explicitly asked from us by the polish team, I guess so they could build some tooling on top, maybe to monitor readiness and automatically fetch errors from the agent's log. I'll add a big fat comment about it to the deployment file.
> 
> Yeah, I understand this, and I think it's fine. But better to document that we're doing some special trickery here. Thx

Yup, I totally agree. Added big fat warning to the deployment file and documented how a readiness probe is used by the stock/sample deployment file to reflect the status of the last configuration update.

**Review by marquiz — APPROVED** [review]
Thanks @klihub! I think this is good now 👍
LGTM

**Comment by klihub** [comment]
@marquiz Let's hold this for a wee bit more. I have something cooking that might be worth taking a look at... if I manage to finish it by tomorrow.

**Comment by klihub** [comment]
> @marquiz Let's hold this for a wee bit more. I have something cooking that might be worth taking a look at... if I manage to finish it by tomorrow.

Okay, so I think the extra bits on top of this (using a ConfigMap-like CRD and propagate detailed error information back after failed updates to the source CR's node-specific parts of its Status field) will have to wait for another PR. It needs more testing and polishing, so it can't be reasonably squeezed into this PR.

**Review by askervin — APPROVED** [review]
LGTM.

**Review by jukkar — APPROVED** [review]

**Pull request merged**
