### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by marquiz**
- kubernetes v1.24.1 -> 1.25.4
- goresctrl v0.2.1-X -> v0.3.0
- contrib.go.opencensus.io/exporter/prometheus v0.1.1-X -> v0.4.2
- contrib.go.opencensus.io/exporter/jaeger v0.1.0 -> v0.2.1
- golang.org/x/net -> v0.2.0
- golang.org/x/time -> v0.2.0

### CODE REVIEW

**Review by klihub — DISMISSED** [review]
LGTM

**Comment by marquiz** [comment]
ping @askervin @jukkar

**Review by jukkar — DISMISSED** [review]

**Comment by marquiz** [comment]
Added one more patch to update `golang.org/x/net` and `golang.org/x/time`, too

**Comment by marquiz** [comment]
@klihub PTAL

**Review by klihub — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]

**Pull request merged**
