### PR TITLE
packaging/: drop agent and webhook from deb packages

### PR DESCRIPTION
**Pull request by marquiz**
Align with other packages i.e. rpm and the binary tarball.

### CODE REVIEW

**Review by klihub — APPROVED** [review]
LGTM

**Review by askervin — APPROVED** [review]
LGTM

**Review by jukkar — APPROVED** [review]

**Review by klihub — APPROVED** [review]
LGTM

**Comment by marquiz** [comment]
Rebased. PTAL

**Review by jukkar — APPROVED** [review]

**Pull request merged**
